### ISSUE TITLE
请问为什么我安装不了呢  

### ISSUE THREAD

**Issue by liuguodong1019** [myloveGy/examination#1]
安装的时候点击提交都没有反应

**Comment by myloveGy** [comment]
你直接把sql 导到你数据库吧！可能安装文件有问题

**Comment by liuguodong1019** [comment]
![image](https://user-images.githubusercontent.com/27914296/43558286-4681582e-963b-11e8-9aa5-6e6e64664685.png)

**Comment by myloveGy** [comment]
你是哪个页面报错！执行composer update 没有

**Comment by liuguodong1019** [comment]
我不是用composer 安装的，我直接下载的压缩包  ，运行web下的index.phpb报错，好像好多命名空间多是错的  但我又找搜不到那个文件

**Comment by myloveGy** [comment]
需要用 composer 安装，你下载的压缩包只是框架基础包！ 你需要执行 composer update 安装其他依赖包

**Comment by liuguodong1019** [comment]
还是一样的错误

**Comment by myloveGy** [comment]
你是拉的我的代码执行的吗？你的 composer.json 文件是不是你修改了！ 你执行 composer require jinxing/yii2-admin

**Comment by liuguodong1019** [comment]
![image](https://user-images.githubusercontent.com/27914296/43584057-dcad3a68-9693-11e8-8b4a-0d5ca373bb20.png)
我想哭了   大哥

**Comment by liuguodong1019** [comment]
我用git是拉不下来的  提示我没有权限 ，得加公钥， 我只能下载压缩包

**Comment by myloveGy** [comment]
你没有github 账号吗？ 821901008 我QQ

**Comment by liuguodong1019** [comment]
有的
