### ISSUE TITLE
有没有thinkphp版本的？

### ISSUE THREAD

**Issue by jiangyouhong** [myloveGy/examination#2]
有没有thinkphp版本的？

**Comment by jiangyouhong** [comment]
我composer update 好慢啊，依赖框架就下载不下来，哎。

**Comment by myloveGy** [comment]
没有 ThinkPHP 版本， composer update 慢是因为 yii2 的镜像问题 ； [composer 镜像使用中国镜像](https://pkg.phpcomposer.com/)
