### ISSUE TITLE
通用部署方案

### ISSUE THREAD

**Issue by yyqyu** [myloveGy/examination#4]
请问下，可否出一个非composer部署的方案呀？composer部署好多问题

**Comment by myloveGy** [comment]
可以！composer 部署问题！一般都是网络不好，可以设置下使用中国镜像！还有就是可能没有安装 [Composer Asset插件:](https://github.com/fxpio/composer-asset-plugin)

    ```

    php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"

    ```
打包文件下载地址：
 * [百度网盘](https://pan.baidu.com/s/1QoAOWuZ0ezhpsO8BMi959A)
 * [有道云笔记](https://note.youdao.com/ynoteshare1/index.html?id=64a4971336b8cc94d2239f4d6c1e4ecb&type=note)
