### ISSUE TITLE
我是一名普通用户，还是不会具体的安装步骤

### ISSUE THREAD

**Issue by mayaren888** [myloveGy/examination#5]
我是windows7的操作系统，使用upupw的绿色环境php5.5的环境。
看到您简单的安装表述还是不太会，能不能针对软件部署这块再细致一些呢？
希望能得到帮助，目前我一直没有部署好。
![微信图片_20191012121729](https://user-images.githubusercontent.com/6006653/66694816-60ad8e00-ecea-11e9-8910-955c43968c99.png)
我把百度网盘中examination的目录整个拷贝到web环境下  之后就不知道该怎么做了，mysql已经部署好了，数据库这块没问题，就是不知道web 这块如何部署。

**Comment by myloveGy** [comment]
不知你有没有PHP基础、或者Yii2 的基础；安装配置环境可以[参考文档](https://www.yiichina.com/doc/guide/2.0/start-installation#configuring-web-servers) 
* 一、在配置虚拟目录这一步，虚拟目录配置好(apache 参考apache的配置、nginx 参考nginx 配置) 虚拟环境的目录要配置到 examination/web 下面

apache 配置
```

<VirtualHost *:80>
    ServerName 域名
    DocumentRoot 你的项目目录地址/examintion/web
    <Directory "你的项目目录地址/examintion/web">
       # 开启 mod_rewrite 用于美化 URL 功能的支持（译注：对应 pretty URL 选项）
    RewriteEngine on
    # 如果请求的是真实存在的文件或目录，直接访问
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # 如果请求的不是真实文件或目录，分发请求至 index.php
    RewriteRule . index.php

    # if $showScriptName is false in UrlManager, do not allow accessing URLs with script name
    RewriteRule ^index.php/ - [L,R=404]
    </Directory>
</VirtualHost>
```

* 二、在mysql 中创建一个数据库，导入项目下 的docs/examination.sql 文件
* 三、在项目下 examination 下的 config 目录下 添加配置数据库配置 db.php 文件，内容如下：
```php
<?php

return [
    'class'       => 'yii\db\Connection',
    'dsn'         => 'mysql:host=localhost;dbname=你添加的库名称',
    'username'    => '数据库用户名称',
    'password'    => '数据库用户密码',
    'charset'     => 'utf8',
    'tablePrefix' => 'ks_',
];
```
