### ISSUE TITLE
没有vendor目录啊，而且我加上也报错了

### ISSUE THREAD

**Issue by Zifengest** [myloveGy/examination#6]
![image](https://user-images.githubusercontent.com/53044059/66982704-4d832f80-f0e9-11e9-9144-b46242e60946.png)

**Comment by myloveGy** [comment]
使用composer install 安装 vendor 目录 ！ 你在config/目录下面 添加 db.php 配置信息没有

 

发件人: Zifengkkk <notifications@github.com>
答复: myloveGy/examination <reply@reply.github.com>
日期: 2019年10月17日 星期四 下午2:21
收件人: myloveGy/examination <examination@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [myloveGy/examination] 没有vendor目录啊，而且我加上也报错了 (#6)
