### ISSUE TITLE
你好，有问题想请教

### ISSUE THREAD

**Issue by bangwanliudian** [myloveGy/examination#7]
新年好！
我下载打包文件(最新) 下载后，从第3步开始，成功导入了SQL。
 且config 中正确添加 db.php 文件。

第四部：配置虚拟目录(需要开启路由重写)，后台地址：域名/admin

第四部，这个这个不清楚该如何配置，我用的是phpstudy
我将"examination"、“__MACOSX”放在我的服务器http://www.abc.com/ 根目录下

即通过   http://www.abc.com/examination  访问本考试系统项目。
现在没成功。
输入 http://www.abc.com/examination/admin显示 404 - Page Not Found

请问能帮忙分析一下吗

**Comment by myloveGy** [comment]
这个应该是你的路由重写没有配置好，请参考https://www.yiichina.com/doc/guide/2.0/start-installation

里面的部署服务器配置

 

发件人: bangwanliudian <notifications@github.com>
答复: myloveGy/examination <reply@reply.github.com>
日期: 2020年1月26日 星期日 下午4:30
收件人: myloveGy/examination <examination@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [myloveGy/examination] 你好，有问题想请教 (#7)

 

新年好！
我下载打包文件(最新) 下载后，从第3步开始，成功导入了SQL。
且config 中正确添加 db.php 文件。

第四部：配置虚拟目录(需要开启路由重写)，后台地址：域名/admin

第四部，这个这个不清楚该如何配置，我用的是phpstudy
我将"examination"、“__MACOSX”放在我的服务器http://www.abc.com/ 根目录下

即通过 http://www.abc.com/examination 访问本考试系统项目。
现在没成功。
输入 http://www.abc.com/examination/admin显示 404 - Page Not Found

请问能帮忙分析一下吗
