### ISSUE TITLE
登录到后台菜单选项不见了

### ISSUE THREAD

**Issue by yrzs** [myloveGy/examination#8]
fork了一份源码到本地，搭建起来发现，登录到后台没有菜单了

**Comment by myloveGy** [comment]
你是使用超级管理员登录的还是？

**Comment by yrzs** [comment]
> 你是使用超级管理员登录的还是？

超级管理员

**Comment by myloveGy** [comment]
把你的依赖包更新到最新，把你 runtime 目录权限全部777， 然后退出重新登录试下，还有看下你的yii2-debug 的调试信息，是否有查询菜单信息

**Comment by yrzs** [comment]
> 把你的依赖包更新到最新，把你 runtime 目录权限全部777， 然后退出重新登录试下，还有看下你的yii2-debug 的调试信息，是否有查询菜单信息

好的，我试试，谢谢

**Comment by yrzs** [comment]
> 把你的依赖包更新到最新，把你的运行时目录权限全部777，然后退出重新登录试下，还有看下你的yii2-debug的调试信息，是否有查询菜单信息

遇到一些问题，可以加你联系方式吗？

**Comment by myloveGy** [comment]
你可以加QQ群：697549103
